// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)

import UserShowTabController from "./user_show_tab_controller"
application.register("user-show-tab", UserShowTabController)
