require: #追記した規約ファイル読込
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1.0 #Rubyバージョン指定
  NewCops: enable  # バージョンが上がった際に追加されたCopを有効にする
  Exclude: # 検査除外とするディレクトリ・ファイルの指定
    - 'bin/**'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'Gemfile'
    - 'vender/**/*'
    - 'db/**/*'
    - 'app/channels/**/*'
    - 'bin/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'app/helpers/**/*'
Style/Documentation: # classの説明を1行目に記述 
  Enabled: false
Style/FrozenStringLiteralComment: # 文字列リテラルについての警告
  Enabled: false
Style/AsciiComments: # 日本語でのコメント記述
  Enabled: false
Metrics/MethodLength: #メソッド文字数
  Max: 20
Metrics/AbcSize: #abcサイズ
  Max: 25
Layout/LineLength: #一行あたりの文字数
  Max: 125
Naming/PredicateName: #メソッド名設定
  Enabled: false