name: Run erb_lint, rubocop

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

			- name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run rubocop
        run: bundle exec rubocop

			- name: Run erb_lint
        run: bundle exec erblint --lint-all