name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print .rubocop.yml content
      run: cat ${{ github.workspace }}/.rubocop.yml
      run: cat ${{ github.workspace }}/.Gemfile
      run: cat ${{ github.workspace }}/.Gemfile.lock
