name: Run erb_lint, rubocop

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop
        run: rubocop

			- name: Run erb_lint
        run: erblint --lint-all
        