name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          bundler-cache: true

    - name: Print .rubocop.yml content
      run: cat ${{ github.workspace }}/Gemfile
